### ISSUE TITLE
Publish a 2.11.0 version

### ISSUE THREAD

**Issue by vendethiel** [scala-irc-bot/scala-irc-bot#7]
So that we can use scala-irc-bot with 2.11. :)

**Comment by mtgto** [comment]
I try to publish 2.11, but twitter's util-eval does not support 2.11.
Waiting https://github.com/twitter/util/pull/97 to be merged.

**Comment by vendethiel** [comment]
Alright, thanks

**Comment by mosesn** [comment]
Just a heads up--twitter will probably not support util-eval in scala 2.11.  It's sort of a compiler hack, so it's tricky to maintain since it changes with every change to the compiler.  I'd encourage you to switch to [Flags](https://github.com/twitter/util/blob/master/util-app/src/main/scala/com/twitter/app/App.scala), which twitter will definitely maintain in scala 2.11.  There are even reasonably good [docs](http://twitter.github.io/twitter-server/Features.html#flags).

**Comment by vendethiel** [comment]
seems like this project is abandoned anyway...
